"""Renders a DataQualityReport and diagnostic plots to docs/.

Separated from `validation.py` so the quality checks themselves stay
free of matplotlib/file-I/O and are cheap to unit test; this module is
where those side effects live.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import pandas as pd

from fraud_detection.common.config import PROJECT_ROOT
from fraud_detection.common.logger import get_logger
from fraud_detection.data.validation import (
    NUMERICAL_COLUMNS,
    TARGET_COLUMN,
    TRANSACTION_TYPE_COLUMN,
    DataQualityReport,
)

logger = get_logger(__name__)

DEFAULT_REPORT_PATH = PROJECT_ROOT / "docs" / "data_report.md"
DEFAULT_IMAGES_DIR = PROJECT_ROOT / "docs" / "images"


def render_markdown_report(
    report: DataQualityReport, output_path: Path | str = DEFAULT_REPORT_PATH
) -> Path:
    """Write `report` to a markdown file, referencing plots under `images/`."""
    lines: list[str] = [
        "# PaySim Data Quality Report",
        "",
        "_Generated by `fraud-detection validate`. Do not edit by hand — rerun the "
        "command instead._",
        "",
        "## Overview",
        "",
        f"- Rows: {report.row_count:,}",
        f"- Columns: {report.column_count}",
        f"- Duplicate rows: {report.duplicate_row_count:,}",
        f"- Fraud transactions: {report.fraud_count:,} ({report.fraud_percentage}%)",
        f"- Negative amounts: {report.negative_amount_count:,}",
        "",
        "## Missing values",
        "",
    ]

    if report.missing_values:
        lines += ["| column | missing |", "|---|---|"]
        lines += [f"| {col} | {n:,} |" for col, n in report.missing_values.items()]
    else:
        lines.append("No missing values.")

    lines += ["", "## Transaction type distribution", "", "| type | count |", "|---|---|"]
    lines += [f"| {t} | {c:,} |" for t, c in report.transaction_type_counts.items()]

    lines += ["", "## Numerical statistics", ""]
    for col, stats in report.numerical_summary.items():
        lines.append(f"### {col}")
        lines += ["", "| stat | value |", "|---|---|"]
        lines += [f"| {k} | {v:,.2f} |" for k, v in stats.items()]
        lines.append("")

    lines += [
        "## Plots",
        "",
        "![Fraud distribution](images/fraud_distribution.png)",
        "",
        "![Transaction type distribution](images/transaction_type_distribution.png)",
        "",
        "![Amount histogram](images/amount_histogram.png)",
        "",
        "![Correlation heatmap](images/correlation_heatmap.png)",
        "",
    ]

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
    logger.info("wrote data quality report", extra={"path": str(path)})
    return path


def generate_plots(df: pd.DataFrame, output_dir: Path | str = DEFAULT_IMAGES_DIR) -> list[Path]:
    """Save the fixed set of diagnostic plots referenced by the markdown report."""
    directory = Path(output_dir)
    directory.mkdir(parents=True, exist_ok=True)
    paths = [
        _plot_fraud_distribution(df, directory / "fraud_distribution.png"),
        _plot_transaction_type_distribution(df, directory / "transaction_type_distribution.png"),
        _plot_amount_histogram(df, directory / "amount_histogram.png"),
        _plot_correlation_heatmap(df, directory / "correlation_heatmap.png"),
    ]
    logger.info("wrote data quality plots", extra={"count": len(paths), "dir": str(directory)})
    return paths


def _plot_fraud_distribution(df: pd.DataFrame, path: Path) -> Path:
    fig, ax = plt.subplots(figsize=(5, 4))
    counts = df[TARGET_COLUMN].value_counts().rename({0: "legitimate", 1: "fraud"})
    counts.plot(kind="bar", ax=ax, color=["#4C72B0", "#C44E52"])
    ax.set_title("Fraud vs. legitimate transactions")
    ax.set_ylabel("count")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)
    return path


def _plot_transaction_type_distribution(df: pd.DataFrame, path: Path) -> Path:
    fig, ax = plt.subplots(figsize=(6, 4))
    df[TRANSACTION_TYPE_COLUMN].value_counts().plot(kind="bar", ax=ax, color="#4C72B0")
    ax.set_title("Transaction type distribution")
    ax.set_ylabel("count")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)
    return path


def _plot_amount_histogram(df: pd.DataFrame, path: Path) -> Path:
    fig, ax = plt.subplots(figsize=(6, 4))
    clipped = df["amount"].clip(upper=df["amount"].quantile(0.99))
    clipped.plot(kind="hist", bins=50, ax=ax, color="#4C72B0")
    ax.set_title("Transaction amount histogram (clipped at p99)")
    ax.set_xlabel("amount")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)
    return path


def _plot_correlation_heatmap(df: pd.DataFrame, path: Path) -> Path:
    columns = [c for c in (*NUMERICAL_COLUMNS, TARGET_COLUMN) if c in df.columns]
    corr = df[columns].corr()

    fig, ax = plt.subplots(figsize=(6, 5))
    im = ax.imshow(corr, cmap="coolwarm", vmin=-1, vmax=1)
    ax.set_xticks(range(len(corr.columns)))
    ax.set_xticklabels(corr.columns, rotation=45, ha="right")
    ax.set_yticks(range(len(corr.columns)))
    ax.set_yticklabels(corr.columns)
    fig.colorbar(im, ax=ax)
    ax.set_title("Correlation heatmap")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)
    return path
