"""Renders the model comparison report to docs/model_report.md."""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt

from fraud_detection.common.config import PROJECT_ROOT
from fraud_detection.common.logger import get_logger
from fraud_detection.models.training import TrainingRunResult

logger = get_logger(__name__)

DEFAULT_MODEL_REPORT_PATH = PROJECT_ROOT / "docs" / "model_report.md"
DEFAULT_MODEL_COMPARISON_IMAGE_PATH = PROJECT_ROOT / "docs" / "images" / "model_comparison.png"

_COMPARISON_METRICS = ("average_precision", "roc_auc", "recall", "precision", "f1")


def plot_model_comparison(
    results: Sequence[TrainingRunResult],
    output_path: Path | str = DEFAULT_MODEL_COMPARISON_IMAGE_PATH,
) -> Path:
    """Grouped bar chart of validation metrics, one group of bars per model."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    model_names = [r.model_name for r in results]
    x = range(len(model_names))
    bar_width = 0.15

    fig, ax = plt.subplots(figsize=(8, 5))
    for i, metric in enumerate(_COMPARISON_METRICS):
        values = [getattr(r.validation_metrics, metric) for r in results]
        offsets = [xi + i * bar_width for xi in x]
        ax.bar(offsets, values, width=bar_width, label=metric)

    ax.set_xticks([xi + bar_width * (len(_COMPARISON_METRICS) - 1) / 2 for xi in x])
    ax.set_xticklabels(model_names, rotation=20, ha="right")
    ax.set_ylabel("score (validation split)")
    ax.set_title("Model comparison")
    ax.legend(loc="upper right", fontsize="small")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)
    return path


def render_model_report(
    results: Sequence[TrainingRunResult],
    best: TrainingRunResult,
    feature_version: str,
    git_commit: str,
    registered_model_name: str,
    registered_model_version: str,
    output_path: Path | str = DEFAULT_MODEL_REPORT_PATH,
) -> Path:
    """Write the model comparison report; assumes `plot_model_comparison` already ran."""
    lines: list[str] = [
        "# Model Comparison Report",
        "",
        "_Generated by `fraud-detection train`. Do not edit by hand — rerun the "
        "command instead._",
        "",
        "## Overview",
        "",
        f"- Feature version: `{feature_version}`",
        f"- Git commit: `{git_commit}`",
        f"- Best model (by validation average_precision): **{best.model_name}**",
        f"- Registered as: `{registered_model_name}` version `{registered_model_version}`",
        "",
        "Model selection uses **validation** `average_precision` (PR-AUC), not "
        '`accuracy` — with ~0.13% fraud, a model that always predicts "not fraud" '
        "would score ~99.87% accuracy while catching zero fraud. PR-AUC is not "
        "inflated by the large number of easy true negatives the way accuracy and "
        "ROC-AUC can be.",
        "",
        "## Validation metrics",
        "",
        "| model | average_precision | roc_auc | precision | recall | f1 | accuracy |",
        "|---|---|---|---|---|---|---|",
    ]

    for result in results:
        m = result.validation_metrics
        marker = " **←best**" if result.model_name == best.model_name else ""
        lines.append(
            f"| {result.model_name}{marker} | {m.average_precision:.4f} | {m.roc_auc:.4f} "
            f"| {m.precision:.4f} | {m.recall:.4f} | {m.f1:.4f} | {m.accuracy:.4f} |"
        )

    lines += [
        "",
        "## Test metrics (best model only, unused for selection)",
        "",
        "| model | average_precision | roc_auc | precision | recall | f1 | accuracy |",
        "|---|---|---|---|---|---|---|",
    ]
    t = best.test_metrics
    lines.append(
        f"| {best.model_name} | {t.average_precision:.4f} | {t.roc_auc:.4f} "
        f"| {t.precision:.4f} | {t.recall:.4f} | {t.f1:.4f} | {t.accuracy:.4f} |"
    )

    lines += [
        "",
        f"Confusion matrix (test): TP={t.true_positives}, FP={t.false_positives}, "
        f"FN={t.false_negatives}, TN={t.true_negatives}",
        "",
        "## MLflow runs",
        "",
        "| model | run_id |",
        "|---|---|",
    ]
    lines += [f"| {r.model_name} | `{r.run_id}` |" for r in results]

    lines += [
        "",
        "## Plots",
        "",
        "![Model comparison](images/model_comparison.png)",
        "",
    ]

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))
    logger.info("wrote model report", extra={"path": str(path)})
    return path
